version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data  # 永続化するデータのファイルパス
    volumes:
      - ./docker/dynamodb_data:/data  # データの永続化
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local

  ses-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ses_mock
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "13306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  ses-local:
    image: 19992240/aws-ses-local
    environment:
      DATA_SOURCE_URL: jdbc:mysql://ses-mysql:3306/ses_mock
      DATA_SOURCE_USER: docker
      DATA_SOURCE_PASSWORD: docker
    ports:
      - "8005:8080"
    depends_on:
      - ses-mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis:/data"

volumes:
  mysql-db-data:
