server:
  port: 8080
  servlet:
    session:
      timeout: 1800

logging:
  level:
    root: info
    org.springframework.security: info
    org:
      springframework:
        jdbc:
          core: info
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: local
  flyway:
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/create
      - classpath:db/migration/insert
  jpa:
    open-in-view: false
  #  必要に応じてコメントアウトを外す
  #    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: idp_session

  mvc:
    hiddenmethod:
      filter:
        # thymeleafからDELETEメソッドを利用できるようにする
        enabled: true

environments:
  db:
    crypt-key: ${CRYPT_KEY:284d835f8118e791}
    salt: ${CRYPT_SALT:306252e5a01e691f}
  mail:
    from: ${FROM_ADDRESS:test@example.com}