server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.security: info
    jdbc:
      sqlonly: trace
    org:
      springframework:
        jdbc:
          core: info

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/create
      - classpath:db/migration/insert
  jpa:
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        # thymeleafからDELETEメソッドを利用できるようにする
        enabled: true

environments:
  mail:
    from: ${FROM_ADDRESS:test@example.com}