INSERT INTO `oauth2_registered_client`
(
  `id`,
  `client_id`,
  `client_id_issued_at`,
  `client_secret`,
  `client_secret_expires_at`,
  `client_name`,
  `client_authentication_methods`,
  `authorization_grant_types`,
  `redirect_uris`,
  `post_logout_redirect_uris`,
  `scopes`,
  `client_settings`,
  `token_settings`
 )
VALUES
(
	'9c2aa5c6-3e20-413b-823a-74e6a3e608e6',
	'test',
	'2023-10-14 13:53:25',
	'$2a$10$zUMDfs/ddaP9upm2t5k5KexZOQ/TbdHqlZeAM68zDJjpLo8ctbMqy',
	NULL,
	'9c2aa5c6-3e20-413b-823a-74e6a3e608e6',
	'client_secret_post,client_secret_jwt,client_secret_basic',
	'refresh_token,client_credentials,authorization_code',
	'http://127.0.0.1:3000/api/callback,http://127.0.0.1:3000,http://localhost:3000/api/callback,http://localhost:3000',
	'',
	'openid',
	'{\"@class\":\"java.util.Collections$UnmodifiableMap\",\"settings.client.require-proof-key\":false,\"settings.client.require-authorization-consent\":true}',
	'{\"@class\":\"java.util.Collections$UnmodifiableMap\",\"settings.token.reuse-refresh-tokens\":true,\"settings.token.id-token-signature-algorithm\":[\"org.springframework.security.oauth2.jose.jws.SignatureAlgorithm\",\"RS256\"],\"settings.token.access-token-time-to-live\":[\"java.time.Duration\",300.000000000],\"settings.token.access-token-format\":{\"@class\":\"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat\",\"value\":\"self-contained\"},\"settings.token.refresh-token-time-to-live\":[\"java.time.Duration\",3600.000000000],\"settings.token.authorization-code-time-to-live\":[\"java.time.Duration\",300.000000000],\"settings.token.device-code-time-to-live\":[\"java.time.Duration\",300.000000000]}'
);
